insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title1', 'content..', null, SYSDATE, 1, 10, true );
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title2', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title3', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title4', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title5', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title6', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title7', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title8', 'content..', null, SYSDATE, 2, 8 , true);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title9', 'content..', null, SYSDATE, 2, 8 , true);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title10', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title11', 'content..', null, SYSDATE, 2, 8 , true);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title12', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title13', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title14', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title15', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title16', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title17', 'content..', null, SYSDATE, 2, 8 , true);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title18', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title19', 'content..', null, SYSDATE, 2, 8 , true);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title20', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title21', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title22', 'content..', null, SYSDATE, 2, 8 , false);
insert into TB_BOARD ( TITLE, CONTENTS, REG_ID, REG_DATE, COMMUNITY_ID, HIT_COUNT, IS_NOTICE ) values ( 'title23', 'content..', null, SYSDATE, 2, 8 , false);

insert into TB_USER ( USER_ID, USER_NAME, EN_NAME, COMP_PHONE, PHONE, CELL_PHONE, COMPANY, JOB_POSITION, ASSIGNMENT, OFFICER_YN, FAX, ZIP_CODE, ADDRESS, COMP_ZIP_CODE, COMP_ADDRESS, EMAIL, DEPT_ID, PASSWORD ) values ( 'hong', '홍길동', 'hong gil dong', '02-2140-7700', '02-2140-7700', '010-1111-2222','투비소프트', '과장','개발', 'Y','02-2140-7798','223232','서울시 강남구 봉은사로','223232','서울시 강남구 봉은사로','hong@tobesoft.com','DEPT-001','1111');

insert into TB_DEPT ( deptName, memberCount ) values ( '인사팀', 8);
insert into TB_DEPT ( deptName, memberCount ) values ( '영업팀', 12);
insert into TB_DEPT ( deptName, memberCount ) values ( '연구팀', 51);
insert into TB_DEPT ( deptName, memberCount ) values ( '홍보팀', 3);
insert into TB_DEPT ( deptName, memberCount ) values ( '지원팀', 26);


insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '개발표준',10300000,'개발표준','',0,0);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '개발표준 > 공통 기능',10301000,'공통 기능','',1,1);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '개발표준 > 공통 기능 > 개발스크립트 표준', 10301001,'개발 스크립트 표준','sample::sampleScript.xfdl',2,2);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '개발표준 > 공통 기능 > 트랜잭션',10301002,'트랜잭션','sample::sampleTransaction.xfdl',2,3);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '개발표준 > 공통 기능 > 액셀 import/export',10301013,'액셀 import/export','sample::sampleExcel.xfdl',2,4);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '개발표준 > 공통 기능 > 파일 upload/download',10301014,'파일 upload/download','sample::sampleFile.xfdl',2,5);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '개발표준 > 확장 컴포넌트 > 멀티콤보',10302002,'멀티콤보','sample::sampleMultiComboModule.xfdl',2,6);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '개발표준 > 확장 컴포넌트 > Splitter',10302003,'Splitter','sample::sampleSplitter.xfdl',2,7);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '개발표준 > 확장 컴포넌트 > 화면 샘플링 (그리드 디테일)',10302007,'화면 샘플링 (그리드 디테일)','sample::gridDetailList.xfdl',2,8);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인',10100000,'디자인','',0,10);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인 > 가이드',10102000,'가이드','',1,11);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인 > 가이드 > 컴포넌트1',10102001,'컴포넌트1','',2,12);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인 > 가이드 > 컴포넌트2',10102002,'컴포넌트2','',2,13);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인 > 가이드 > 컴포넌트3',10102003,'컴포넌트3','',2,14);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인 > 템플릿',10101000,'템플릿','',1,15);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인 > 템플릿 > Single-Detail',10101001,'Single-Detail','',2,16);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인 > 템플릿 > List-Detail1',10101002,'List-Detail1','',2,17);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인 > 템플릿 > List-Detail2',10101003,'List-Detail2','',2,18);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인 > 템플릿 > Master-Detail',10101004,'Master-Detail','',2,19);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인 > 템플릿 > Master-Detail-V',10101005,'Master-Detail-V','',2,20);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인 > 템플릿 > Master-Detail-H',10101006,'Master-Detail-H','',2,21);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인 > 템플릿 > Master-Detail-VVV',10101010,'Master-Detail-VVV','',2,22);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인 > 템플릿 > Master-List-Detail-VHH',10101011,'Master-List-Detail-VHH','',2,23);
insert into SCC_MENU ( DISPLAY_PATH, MENU_ID, MENU_NM, MENU_URL, MENU_LV, MENU_ORDER ) values ( '디자인 > 템플릿 > Master-List-Detail-HVV',10101012,'Master-List-Detail-HVV','',2,24);