CREATE TABLE TB_BOARD (
     POST_ID INTEGER NOT NULL IDENTITY
    , TITLE VARCHAR(150) NULL
    , CONTENTS LONGVARCHAR NULL
    , REG_ID VARCHAR(20) NULL
    , REG_DATE DATE NULL
    , COMMUNITY_ID VARCHAR(16) NULL
    , HIT_COUNT INTEGER NULL
    , IS_NOTICE BOOLEAN
    , PRIMARY KEY (POST_ID)
);

CREATE TABLE TB_USER (
      USER_ID VARCHAR(50) NOT NULL
    , USER_NAME VARCHAR(50) NOT NULL
    , EN_NAME VARCHAR(20) NULL
    , COMP_PHONE VARCHAR(20) NULL
    , PHONE VARCHAR(20) NULL
    , CELL_PHONE VARCHAR(20) NULL
    , COMPANY VARCHAR(50) NULL
    , JOB_POSITION VARCHAR(20) NULL
    , ASSIGNMENT VARCHAR(20) NULL
    , OFFICER_YN VARCHAR(20) NULL
    , FAX VARCHAR(20) NULL
    , ZIP_CODE VARCHAR(20) NULL
    , ADDRESS VARCHAR(20) NULL
    , COMP_ZIP_CODE VARCHAR(20) NULL
    , COMP_ADDRESS VARCHAR(20) NULL
    , EMAIL VARCHAR(20) NULL
    , DEPT_ID VARCHAR(20) NULL
    , PASSWORD VARCHAR(20) NOT NULL
    , PRIMARY KEY (USER_ID)
);

DROP TABLE IF EXISTS TB_DEPT;
CREATE TABLE TB_DEPT
(
	deptId int NOT NULL IDENTITY
	, deptName VARCHAR(36) NULL
	, memberCount int NULL
    , PRIMARY KEY (deptId)
);

CREATE TABLE SCC_MENU (
      DISPLAY_PATH VARCHAR(100)
    , MENU_ID VARCHAR(50) NOT NULL
    , MENU_NM VARCHAR(100)
    , MENU_URL VARCHAR(100)
    , MENU_LV VARCHAR(5) NOT NULL
    , MENU_ORDER INT
    , PRIMARY KEY (MENU_ID)
);